##################################################
# Create normal users
##################################################
- name: Create normal users
  ansible.windows.win_user:
    name: "{{ item.username }}"
    fullname: "{{ item.fullname }}"
    password: "{{ item.password }}"
    state: present
    groups:
      - Users
  with_items:
    - { username: 'jso-yeon', fullname: "Jeon So-yeon", password: '{{ win_file_server_password }}' }
    - { username: 'lmanoban', fullname: "Lalisa Manoban", password: '{{ win_file_server_password }}' }
    - { username: 'hton', fullname: "Hoang ton", password: '{{ win_file_server_password }}' }

##################################################
# Create admin users
##################################################
- name: Create administrator users
  ansible.windows.win_user:
    name: "{{ item.username }}"
    fullname: "{{ item.fullname }}"
    password: "{{ item.password }}"
    state: present
    groups:
      - Users
      - Administrators
  with_items:
    - { username: 'dengziqi', fullname: "Dèngzǐqí", password: '{{ win_file_server_admin_password }}' }
