##################################################
# Create normal users
##################################################
- name: Create normal users
  ansible.windows.win_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
    groups:
      - Users
  with_items:
    - { username: 'IronMan', password: '{{ win_file_server_password }}' }
    - { username: 'CaptainAmerica', password: '{{ win_file_server_password }}' }
    - { username: 'Thor', password: '{{ win_file_server_password }}' }
    - { username: 'CaptainMarvel', password: '{{ win_file_server_password }}' }

##################################################
# Create admin users
##################################################
- name: Create administrator users
  ansible.windows.win_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
    groups:
      - Users
      - Administrators
  with_items:
    - { username: 'Thanos', password: '{{ win_file_server_admin_password }}' }
    - { username: 'Hulk', password: '{{ win_file_server_admin_password }}' }
    - { username: 'BlackWidow', password: '{{ win_file_server_admin_password }}' }
    - { username: 'HawkEye', password: '{{ win_file_server_admin_password }}' }
