##################################################
# Create public share
##################################################
- name: Create directory structure
  ansible.windows.win_file:
    path: 'C:\shares\{{ item }}'
    state: directory
  with_items:
    - 'public'
    - 'private'

# https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/guest-access-in-smb2-is-disabled-by-default
- name: Enable Guest remote share login
  ansible.windows.win_regedit:
    path: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters"
    name: AllowInsecureGuestAuth
    data: 1
    type: dword

- name: Enable Guest user account
  win_shell: 'net user guest /active:yes'

- name: Add public company share
  ansible.windows.win_share:
    name: public
    description: Files for company employees
    path: C:\shares\public
    list: yes
    full: Everyone,Users,Administrators

##################################################
# Copy files to public share
##################################################
- name: Copy files to private Windows share
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: C:\shares\public
  with_fileglob:
    - "files/exfil_files/public/*.pdf"

##################################################
# Create private share
##################################################
- name: Add secret share
  ansible.windows.win_share:
    name: private
    description: top secret share
    path: C:\shares\private
    list: no
    full: Administrators

##################################################
# Copy files to private share
##################################################
- name: Copy files to private Windows share
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: C:\shares\public
  with_fileglob:
    - "files/exfil_files/*.pdf"