####################################################################
# Install/Setup NGINX
####################################################################
- name: Install NGINX

- name: Generate OpenSSL pub cert and priv key

- name: Copy NGINX.conf
  template:
    src: 'conf/arkmie/nginx/nginx.conf'
    dest: '/etc/nginx/nginx.conf'
    owner: root
    group: root
    mode: 0400

- name: Copy NGINX config for Arkmie
  template:
    src: 'conf/arkmie/nginx/arkmie.conf'
    dest: '/etc/nginx/conf.d/arkmie.conf'
    owner: root
    group: root
    mode: 0400


- name: Start NGINX
  service:
    name: 'nginx'
    enabled: yes
    state: restarted

- name: NGINX healthcheck
  uri:
    url: "https://127.0.0.1:443"
    follow_redirects: none
    method: GET
    validate_certs: 'no'
    status_code: 200
  register: _result
  until: _result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds